---------------------------------------------------------------------------------
-- Dragon Designer Label Deployment version 6.0.0.0
-- 
-- Deployer Log Text File
-- 
-- SCR: InsertTest
-- 
-- Source Repository: Designer Dev - DCOREDD
-- Target Repository: DUMMY For SCR
-- 
-- Generated By:   Pramod Kumar
-- Generated Date: 2021-11-23 19:46:13.838
-- 
-- 0 MAPI transactions added
-- 0 MAPI transactions deployed
-- 0 MAPI transactions skipped
-- 
-- 0 MD transactions added
-- 1 MD transactions deployed
-- 0 MD transactions skipped
-- 
-- 0 required referenced I18N translation keys deployed
-- 0 required referenced I18N translation labels deployed
-- 
-- Refer to the log file '923901_InsertTest_LOG.SQL' for additional information.
-- 
-----BEGIN DATA------------------------------------------------------------------




-- STANDARD METADATA TRANSACTION 858688901 PROCESSED SUCCESSFULLY. SOURCE SCR: InsertTest, TABLE: PAGE_LAYOUT, ROW: 321601. INFO: MERGE statement created successfully.

-- WARNING -- PAGE_LAYOUT {WARNING=Constraints=MissingInMapi=[SYS_C0014549],LogTable="cols":{"SYNCHRONIZED_TF":"Extra in LogTable"}}TRACE:ScrCommitDataInconsistencyException@com.oneshield.tools.businesslogic.BSL_XmlGenerator.addTableSchemaInfo(BSL_XmlGenerator.java:458)MSG:{WARNING=Constraints=MissingInMapi=[SYS_C0014549],LogTable="cols":{"SYNCHRONIZED_TF":"Extra in LogTable"}}


-----END DATA--------------------------------------------------------------------
-- 
-- End of Deployer Log Text File file for SCR InsertTest
